{% set name = "openhexa.toolbox" %}
{% set version = "1.4.3" %}
{% set sha = "320a0759b857c4f191c3fa13890436d38fd08e8779d98bdc55c87e5c705db8e9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/openhexa_toolbox-{{ version }}.tar.gz
  sha256: {{ sha }}

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools
    - wheel
    - pip
  run:
    - python >=3.8
    - requests
    - python-dateutil
    - pandas
    - shapely
    - geopandas
    - polars
    - diskcache
    - pyjwt
    - cdsapi >=0.7.3
    - cads-api-client >=1.4.0
    - rasterio
    - cfgrib
    - xarray
    - epiweeks

test:
  imports:
    - openhexa.toolbox
  commands:
    - pip check
  requires:
    - pip

about:
  summary: A set of tools to acquire & process data from various sources
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - qgerome
