{% set name = "openhexa.toolbox" %}
{% set version = "1.1.0" %}
{% set sha = "187df6ebbc718d6aa9498b1b897c84cddae4c23f05c3de9d8a9a656dae304bbb" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/openhexa_toolbox-{{ version }}.tar.gz
  sha256: {{ sha }}

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools
    - wheel
    - pip
  run:
    - python >=3.8
    - requests
    - python-dateutil
    - pandas
    - shapely
    - geopandas
    - polars
    - diskcache
    - pyjwt

test:
  imports:
    - openhexa.toolbox
  commands:
    - pip check
  requires:
    - pip

about:
  summary: A set of tools to acquire & process data from various sources
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - qgerome
