{% set name = "openhexa.toolbox" %}
{% set version = "0.2.5" %}
{% set sha = "9ae2b54045a665c34d0df74dda997939df1f285aabe9a65c768bcf7b049de1ea" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/openhexa_toolbox-{{ version }}.tar.gz
  sha256: {{ sha }}

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools
    - wheel
    - pip
  run:
    - python >=3.8
    - requests
    - python-dateutil
    - pandas
    - shapely
    - geopandas
    - polars
    - diskcache
    - pyjwt

test:
  imports:
    - openhexa.toolbox
  commands:
    - pip check
  requires:
    - pip

about:
  summary: A set of tools to acquire & process data from various sources
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - qgerome
