{% set name = "openhexa.sdk" %}
{% set version = '0.3.0' %}
{% set sha = "fcaf8dc8c99801d33bcdce8671aeba2ca74b94261e1b538579e3cba2e23880dc" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/openhexa_sdk-{{ version }}.tar.gz
  sha256: {{ sha }}

build:
  entry_points:
    - openhexa = openhexa.cli:app
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.9,<3.13
    - setuptools
    - wheel
    - pip
  run:
    - python>=3.9,<3.13
    - urllib3<2
    - multiprocess>=0.70.15,<0.71.dev0
    - requests>=2.31
    - pyyaml
    - click>=8.1.3,<8.2.dev0
    - jinja2>3,<4
    - docker-py

test:
  imports:
    - openhexa.sdk
  commands:
    - openhexa --help
    - pip check
  requires:
    - pip

about:
  summary: OpenHEXA SDK
  license: 'MIT'
  license_file: LICENCE

extra:
  recipe-maintainers:
    - qgerome
